.PHONY: clean All

All:
	@echo "----------Building project:[ Caller - Release ]----------"
	@cd "Caller" && "$(MAKE)" -f  "Caller.mk"
clean:
	@echo "----------Cleaning project:[ Caller - Release ]----------"
	@cd "Caller" && "$(MAKE)" -f  "Caller.mk" clean
